### PR TITLE
Implemented Worker-based timer

### PR DESCRIPTION
**Pull request by cwilso**

### CODE REVIEW

**Comment by xerosanyam** [comment]
what was the usecase for implementing this ?

**Comment by uhoh-itsmaciek** [comment]
Hi @cwilso, thanks for the neat demo (and the great "Tale of Two Clocks" article). Do you have any more info on this change? I understand the code, but I don't fully understand the motivation. Is the idea just that the worker approach makes it easier to adjust the interval while the metronome is running? Or is it about avoiding work on the main thread? Curious to learn more if you could point me in the right direciton.

**Comment by cwilso** [comment]
Oof, I really should have updated that article.

So, on the main thread, setTimeout gets throttled whenever the window is not in focus - so, even if you set a timeout for ever 100ms, you'll only get a callback once every second.  However, setTimeouts on worker threads DON'T get throttled - even if they call back to the main thread - so it's possible to keep consistent timing that way, while still doing the timer call more frequently than once every second.

(The throttling was originally implemented to avoid power drain from animation that was implemented before requestAnimationFrame().)

**Comment by uhoh-itsmaciek** [comment]
Thanks for the quick response! That makes a lot of sense.

>Oof, I really should have updated that article.

It's not too late :wink:

**Pull request merged**
